#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6444456083                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://mic.st                            # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your plant organizer, fast and simple with privacy in mind.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Michael Steudter                                
your_link                                 : https://mic.st                     
your_city                                 : Düsseldorf                                
email_address                             : contact@mic.st
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : florra_app
github_username                           : misteu
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Save your Plants in Florra 
    description                           : Create plants, with custom names, descriptions and photos.
    fontawesome_icon_name                 : leaf

  - title                                 : AI Identification for adding Plants
    description                           : "*PREMIUM:* Quickly create new plants by taking a photo of your plant or choose an existing one from your gallery. Choose from common or scientific plant names!"
    fontawesome_icon_name                 : magic

  - title                                 : Organize your Plants
    description                           : Easily group multiple plants into groups using drag and drop gestures or via the plant's details screen.
    fontawesome_icon_name                 : objects

  - title                                 : Add Reminders for any Plant or Group of Plants
    description                           : Create one-time or recurring reminders for your plants. All of today's reminders are shown on your overview, see all of your reminders via the "Notifications" tab.
    fontawesome_icon_name                 : bell

  - title                                 : Manage your own Plant Diary
    description                           : "*PREMIUM:* Create diary entries that can be associated with your plants or groups of plants. Add photos to your entries for a more lively diary, to track growth etc."
    fontawesome_icon_name                 : book

  - title                                 : Filter your Diary
    description                           : "*PREMIUM:* Your diary has simple to use filters that let you filter you entries by year, plant, group or category."
    fontawesome_icon_name                 : filter

  - title                                 : Add your own Categories
    description                           : "*PREMIUM:* Get even more creative and efficient by adding your own categories. They can be used to categorize notifications or diary entries. The diary filter is automatically able to use your custom categories!"
    fontawesome_icon_name                 : shapes

  - title                                 : Everything is local, no Internet connection needed!
    description                           : All data is saved on your device and stays on your device. Therefore all your data is instantly available!
    fontawesome_icon_name                 : house

  - title                                 : Privacy First
    description                           : None of your created content is ever uploaded anywhere. More Privacy friendly analytics (Telemetry Deck) is used instead of Google services.
    fontawesome_icon_name                 : user-shield

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
